NYKalleMaintV01/Models/tblSpil.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYKalleMaintV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSpil()
        {
            this.CN_SpilSesson = 0;
            this.CN_SpilPlacering = 0;
            this.CN_SpilGennemsnit = 0m;
            this.tblFrames = new HashSet<tblFrame>();
        }
    
        public int CN_SpilPK { get; set; }
        public int CN_SpilSpillerPK { get; set; }
        public System.DateTime CN_SpilDato { get; set; }
        public int CN_SpilSesson { get; set; }
        public Nullable<bool> CN_SpilKalleKamel { get; set; }
        public int CN_SpilPlacering { get; set; }
        public decimal CN_SpilGennemsnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFrame> tblFrames { get; set; }
        public virtual tblSpiller tblSpiller { get; set; }
    }
}

NYKalleMaintV01/Controllers/tblFrameController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NYKalleMaintV01.Models;

namespace NYKalleMaintV01.Controllers
{
    public class tblFrameController : Controller
    {
        private NyKalleEntities db = new NyKalleEntities();

        // GET: tblFrame
        public ActionResult Index(int URLspillerId, int URLspilId)
        {

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId, URLspilId);

            List<tblFrame> ListFrame = db.tblFrames.Where(t => t.CN_FrameSpilPK == URLspilId).ToList();

            return View(ListFrame);
        }

        // GET: tblFrame/Details/5
        public ActionResult Details(int? id, int URLspillerId, int URLspilId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFrame tblFrame = db.tblFrames.Find(id);
            if (tblFrame == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId, URLspilId);

            return View(tblFrame);
        }

        // GET: tblFrame/Create
        public ActionResult Create(int URLspillerId, int URLspilId)
        {

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId, URLspilId);

            // Der skal ikke laves en drop down liste, der er valgt
            // ViewBag.CN_FrameSpilPK = new SelectList(db.tblSpils, "CN_SpilPK", "CN_SpilPK");

            return View();
        }

        // POST: tblFrame/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int URLspillerId, int URLspilId,[Bind(Include = "CN_FramePK,CN_FrameSpilPK,CN_FrameScore")] tblFrame tblFrame)
        {
            if (ModelState.IsValid)
            {

                tblFrame.CN_FrameSpilPK = URLspilId;

                db.tblFrames.Add(tblFrame);
                db.SaveChanges();
                return RedirectToAction("Index", new { URLspillerId, URLspilId });
            }

            ViewBag.CN_FrameSpilPK = new SelectList(db.tblSpils, "CN_SpilPK", "CN_SpilPK", tblFrame.CN_FrameSpilPK);
            return View(tblFrame);
        }

        // GET: tblFrame/Edit/5
        public ActionResult Edit(int? id, int URLspillerId, int URLspilId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFrame tblFrame = db.tblFrames.Find(id);
            if (tblFrame == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId, URLspilId);

            // Skal ikke bruges, der er valgt spil
            //ViewBag.CN_FrameSpilPK = new SelectList(db.tblSpils, "CN_SpilPK", "CN_SpilPK", tblFrame.CN_FrameSpilPK);

            return View(tblFrame);
        }

        // POST: tblFrame/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int URLspillerId, int URLspilId, [Bind(Include = "CN_FramePK,CN_FrameSpilPK,CN_FrameScore")] tblFrame tblFrame)
        {
            if (ModelState.IsValid)
            {

                tblFrame.CN_FrameSpilPK = URLspilId;

                db.Entry(tblFrame).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { URLspillerId, URLspilId });
            }
            ViewBag.CN_FrameSpilPK = new SelectList(db.tblSpils, "CN_SpilPK", "CN_SpilPK", tblFrame.CN_FrameSpilPK);
            return View(tblFrame);
        }

        // GET: tblFrame/Delete/5
        public ActionResult Delete(int? id, int URLspillerId, int URLspilId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblFrame tblFrame = db.tblFrames.Find(id);
            if (tblFrame == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId, URLspilId);

            return View(tblFrame);
        }

        // POST: tblFrame/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int URLspillerId, int URLspilId)
        {
            tblFrame tblFrame = db.tblFrames.Find(id);
            db.tblFrames.Remove(tblFrame);
            db.SaveChanges();
            return RedirectToAction("Index", new { URLspillerId, URLspilId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Hent Fornavn og Efternavn på spiller
        private string FnHentNavneOpl(int URLspillerId, int URLspilId)
        {
            if (URLspillerId == 0)
            {
                return ("Du kalder med værdien: 0, derfor ikke noget navn til dig basta!!!.");
            }
            if (URLspilId == 0)
            {
                return ("Du kalder med værdien: 0, derfor ikke noget spil til dig bum!!!.");
            }

            ViewBag.URLspillerId = URLspillerId;
            ViewBag.URLspilId = URLspilId;

            var spillerInfo = db.tblSpillers.FirstOrDefault(t => t.CN_SpillerPK == URLspillerId);
            return (spillerInfo.CN_SpillerForNavn + " " + spillerInfo.CN_SpillerEfterNavn);
        }
        
        // Nu skal der beregnes gennemsnit af dagen for spillene (Frame)
        public ActionResult FnBeregnGennemsnit(int URLspillerId, int URLspilId)
        {
            //Først skal der opsummeres:

            // Først lidt housekeeping.
            decimal Gennemsnit = 0;
            int AntFrames = 0;

            //Hent de Frames der er tale om.
            List<tblFrame> ListFrame = db.tblFrames.Where(t => t.CN_FrameSpilPK == URLspilId).ToList();

            //Så skal der lige løbes igennem og findes gennemsnit:
            foreach (var item in ListFrame)
            {
                Gennemsnit = Gennemsnit + item.CN_FrameScore;
                AntFrames = AntFrames + 1;
            }
            //Så skal der lige regnes lidt på det.
            if (AntFrames > 0)
            {
                Gennemsnit = Gennemsnit / AntFrames;
            }

            //Klar til opdatering af tblSpil
            tblSpil tblSpil = db.tblSpils.Find(URLspilId);

            if (tblSpil != null)
            {
                tblSpil.CN_SpilGennemsnit = Gennemsnit;

                db.Entry(tblSpil).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index", "tblSpil", new { URLspillerId });
         }
    }
}

NYKalleMaintV01/Controllers/tblSpilController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NYKalleMaintV01.Models;

namespace NYKalleMaintV01.Controllers
{
    public class tblSpilController : Controller
    {
        private NyKalleEntities db = new NyKalleEntities();

        // GET: tblSpil
        public ActionResult Index(int URLspillerId)
        {
            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            List<tblSpil> ListSpil = db.tblSpils.OrderByDescending(t => t.CN_SpilDato).Where(t => t.CN_SpilSpillerPK == URLspillerId).ToList();
            return View(ListSpil);
        }

        // GET: tblSpil/Details/5
        public ActionResult Details(int? id, int URLspillerId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpil tblSpil = db.tblSpils.Find(id);
            if (tblSpil == null)
            {
                return HttpNotFound();
            }
            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            return View(tblSpil);
        }

        // GET: tblSpil/Create
        public ActionResult Create(int URLspillerId)
        {
            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            // Skal ikkebenytte en list, Spilleren er udpeget og kun de spil som spilleren har skal listes
            // ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn");

            return View();
        }

        // POST: tblSpil/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int URLspillerId, [Bind(Include = "CN_SpilPK,CN_SpilSpillerPK,CN_SpilDato,CN_SpilSesson,CN_SpilKalleKamel,CN_SpilPlacering,CN_SpilGennemsnit")] tblSpil tblSpil)
        {
            if (ModelState.IsValid)
            {
                tblSpil.CN_SpilSpillerPK = URLspillerId;

                db.tblSpils.Add(tblSpil);
                db.SaveChanges();
                return RedirectToAction("Index", new { URLspillerId = tblSpil.CN_SpilSpillerPK });
            }

            // Spilleren er allerede valgt
            // ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn", tblSpil.CN_SpilSpillerPK);

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            return View(tblSpil);
        }

        // GET: tblSpil/Edit/5
        public ActionResult Edit(int? id, int URLspillerId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpil tblSpil = db.tblSpils.Find(id);
            if (tblSpil == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            // Skal ikke bruges. Spiller er valgt
            // ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn", tblSpil.CN_SpilSpillerPK);

            return View(tblSpil);
        }

        // POST: tblSpil/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int URLspillerId, [Bind(Include = "CN_SpilPK,CN_SpilSpillerPK,CN_SpilDato,CN_SpilSesson,CN_SpilKalleKamel,CN_SpilPlacering,CN_SpilGennemsnit")] tblSpil tblSpil)
        {
            if (ModelState.IsValid)
            {
                tblSpil.CN_SpilSpillerPK = URLspillerId;

                db.Entry(tblSpil).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", new { URLspillerId });
            }
            ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn", tblSpil.CN_SpilSpillerPK);
            return View(tblSpil);
        }

        // GET: tblSpil/Delete/5
        public ActionResult Delete(int? id, int URLspillerId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpil tblSpil = db.tblSpils.Find(id);
            if (tblSpil == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            return View(tblSpil);
        }

        // POST: tblSpil/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int URLspillerId)
        {
            tblSpil tblSpil = db.tblSpils.Find(id);
            db.tblSpils.Remove(tblSpil);
            db.SaveChanges();
            return RedirectToAction("Index", new { URLspillerId });
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        // Hent Fornavn og Efternavn på spiller
        private string FnHentNavneOpl(int URLspillerId)
        {
            if (URLspillerId == 0)
            {
                return ("Du kalder med værdien: 0, derfor ikke noget navn til dig basta.");
            }

            ViewBag.URLspillerId = URLspillerId;

            var spillerInfo = db.tblSpillers.FirstOrDefault(t => t.CN_SpillerPK == URLspillerId);
            return (spillerInfo.CN_SpillerForNavn + " " + spillerInfo.CN_SpillerEfterNavn);
        }
    }
}

NYKalleMaintV01/Views/tblSpil/Create.cshtml
@model NYKalleMaintV01.Models.tblSpil

@{
    ViewBag.Title = "Create";
}

<h2>Create Spil - @ViewBag.SpillerNavn</h2>

<div>
    @Html.ActionLink("Back to List", "Index", new { URLspillerId = ViewBag.URLspillerId }) 
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
    @* Skal ikke bruges. Spilleren er allerede valgt.
        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilSpillerPK, "CN_SpilSpillerPK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CN_SpilSpillerPK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CN_SpilSpillerPK, "", new { @class = "text-danger" })
            </div>
        </div>
    *@       
        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilDato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilDato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilDato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilSesson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilSesson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilSesson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilKalleKamel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpilKalleKamel)
                    @Html.ValidationMessageFor(model => model.CN_SpilKalleKamel, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilPlacering, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilPlacering, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilPlacering, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilGennemsnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilGennemsnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilGennemsnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

NYKalleMaintV01/Views/tblSpil/Delete.cshtml
@model NYKalleMaintV01.Models.tblSpil

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Spil - @ViewBag.SpillerNavn</h2>

<div>
    @Html.ActionLink("Back to List", "Index", new { URLspillerId = ViewBag.URLspillerId })
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilDato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilDato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilSesson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilSesson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilKalleKamel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilKalleKamel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilPlacering)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilPlacering)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilGennemsnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilGennemsnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSpiller.CN_SpillerForNavn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSpiller.CN_SpillerForNavn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

NYKalleMaintV01/Views/tblSpil/Details.cshtml
@model NYKalleMaintV01.Models.tblSpil

@{
    ViewBag.Title = "Details";
}

<h2>Details Spil - @ViewBag.SpillerNavn</h2>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CN_SpilPK, URLspillerId = ViewBag.URLspillerId }) |
    @Html.ActionLink("Back to List", "Index", new { URLspillerId = ViewBag.URLspillerId })
</div>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilDato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilDato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilSesson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilSesson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilKalleKamel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilKalleKamel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilPlacering)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilPlacering)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpilGennemsnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpilGennemsnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSpiller.CN_SpillerForNavn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSpiller.CN_SpillerForNavn)
        </dd>

    </dl>
</div>

NYKalleMaintV01/Views/tblSpil/Edit.cshtml
@model NYKalleMaintV01.Models.tblSpil

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Spil - @ViewBag.SpillerNavn</h2>
<div>
    @Html.ActionLink("Back to List", "Index", new { URLspillerId = ViewBag.URLspillerId })
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CN_SpilPK)

        @*<div class="form-group">
            @Html.LabelFor(model => model.CN_SpilSpillerPK, "CN_SpilSpillerPK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CN_SpilSpillerPK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CN_SpilSpillerPK, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilDato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilDato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilDato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilSesson, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilSesson, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilSesson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilKalleKamel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpilKalleKamel)
                    @Html.ValidationMessageFor(model => model.CN_SpilKalleKamel, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilPlacering, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilPlacering, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilPlacering, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpilGennemsnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpilGennemsnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpilGennemsnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

NYKalleMaintV01/Views/tblSpil/Index.cshtml
@model IEnumerable<NYKalleMaintV01.Models.tblSpil>

@{
    ViewBag.Title = "Index";
}

<h2>Index Spil - @ViewBag.SpillerNavn</h2>

<div>
    @Html.ActionLink("Create New", "Create", new { URLspillerId = ViewBag.URLspillerId }) |
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpilDato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpilSesson)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpilKalleKamel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpilPlacering)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpilGennemsnit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tblSpiller.CN_SpillerForNavn)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpilDato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpilSesson)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpilKalleKamel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpilPlacering)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpilGennemsnit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblSpiller.CN_SpillerForNavn)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CN_SpilPK, URLspillerId = ViewBag.URLspillerId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CN_SpilPK, URLspillerId = ViewBag.URLspillerId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CN_SpilPK, URLspillerId = ViewBag.URLspillerId }) |
            @Html.ActionLink("Frame", "Index", "tblFrame", new { URLspillerId = ViewBag.URLspillerId, URLspilId = item.CN_SpilPK }, null )
            @* Jørn har vist mig denne: <a href="@Url.Action( "Index", "tblFrame", new { id=-1, URLspillerId = ViewBag.URLspillerId, URLspilId = item.CN_SpilPK } )">Frame</a>*@
        </td>
    </tr>
}

</table>