NYKalleMaintV01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NYKalleMaintV01.Models;

namespace NYKalleMaintV01.Controllers
{
    public class HomeController : Controller
    {
        private NyKalleEntities db = new NyKalleEntities();

        // GET: Home
        public ActionResult Index()
        {
            return View(db.tblSpillers.OrderByDescending(y => y.CN_AktivMedl).ThenBy(y => y.CN_SpillerForNavn).ToList());
        }

        // GET: Home/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpiller tblSpiller = db.tblSpillers.Find(id);
            if (tblSpiller == null)
            {
                return HttpNotFound();
            }
            return View(tblSpiller);
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View(new tblSpiller());
        }

        // POST: Home/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CN_SpillerPK,CN_SpillerForNavn,CN_SpillerEfterNavn,CN_SpillerInit,CN_SpillerOptDato,CN_SpillerUdMeldDato,CN_SpillerFormand,CN_SpillerNastFormand,CN_SpillerKasser,CN_SpillerRevisor,CN_SpillerSkemaAnsv,CN_SpillerWebAnsv,CN_EMail,CN_AktivMedl,CN_PassivMedl,CN_ProveMedl")] tblSpiller tblSpiller)
        {
            if (ModelState.IsValid)
            {
                db.tblSpillers.Add(tblSpiller);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblSpiller);
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpiller tblSpiller = db.tblSpillers.Find(id);
            if (tblSpiller == null)
            {
                return HttpNotFound();
            }
            return View(tblSpiller);
        }

        // POST: Home/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CN_SpillerPK,CN_SpillerForNavn,CN_SpillerEfterNavn,CN_SpillerInit,CN_SpillerOptDato,CN_SpillerUdMeldDato,CN_SpillerFormand,CN_SpillerNastFormand,CN_SpillerKasser,CN_SpillerRevisor,CN_SpillerSkemaAnsv,CN_SpillerWebAnsv,CN_EMail,CN_AktivMedl,CN_PassivMedl,CN_ProveMedl")] tblSpiller tblSpiller)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblSpiller).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblSpiller);
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpiller tblSpiller = db.tblSpillers.Find(id);
            if (tblSpiller == null)
            {
                return HttpNotFound();
            }
            return View(tblSpiller);
        }

        // POST: Home/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblSpiller tblSpiller = db.tblSpillers.Find(id);
            db.tblSpillers.Remove(tblSpiller);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NYKalleMaintV01/Controllers/tblSpilController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NYKalleMaintV01.Models;

namespace NYKalleMaintV01.Controllers
{
    public class tblSpilController : Controller
    {
        private NyKalleEntities db = new NyKalleEntities();

        // GET: tblSpil
        public ActionResult Index(int URLspillerId)
        {
            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            List<tblSpil> ListSpil = db.tblSpils.OrderByDescending(t => t.CN_SpilDato).Where(t => t.CN_SpilSpillerPK == URLspillerId).ToList();
            return View(ListSpil);
        }

        // GET: tblSpil/Details/5
        public ActionResult Details(int? id, int URLspillerId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpil tblSpil = db.tblSpils.Find(id);
            if (tblSpil == null)
            {
                return HttpNotFound();
            }
            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            return View(tblSpil);
        }

        // GET: tblSpil/Create
        public ActionResult Create(int URLspillerId)
        {
            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            // Skal ikkebenytte en list, Spilleren er udpeget og kun de spil som spilleren har skal listes
            // ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn");

            return View();
        }

        // POST: tblSpil/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int URLspillerId, [Bind(Include = "CN_SpilPK,CN_SpilSpillerPK,CN_SpilDato,CN_SpilSesson,CN_SpilKalleKamel,CN_SpilPlacering,CN_SpilGennemsnit")] tblSpil tblSpil)
        {
            if (ModelState.IsValid)
            {
                tblSpil.CN_SpilSpillerPK = URLspillerId;

                db.tblSpils.Add(tblSpil);
                db.SaveChanges();
                return RedirectToAction("Index", new { URLspillerId = tblSpil.CN_SpilSpillerPK });
            }

            // Spilleren er allerede valgt
            // ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn", tblSpil.CN_SpilSpillerPK);

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            return View(tblSpil);
        }

        // GET: tblSpil/Edit/5
        public ActionResult Edit(int? id, int URLspillerId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpil tblSpil = db.tblSpils.Find(id);
            if (tblSpil == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            // Skal ikke bruges. Spiller er valgt
            // ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn", tblSpil.CN_SpilSpillerPK);

            return View(tblSpil);
        }

        // POST: tblSpil/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int URLspillerId, [Bind(Include = "CN_SpilPK,CN_SpilSpillerPK,CN_SpilDato,CN_SpilSesson,CN_SpilKalleKamel,CN_SpilPlacering,CN_SpilGennemsnit")] tblSpil tblSpil)
        {
            if (ModelState.IsValid)
            {
                tblSpil.CN_SpilSpillerPK = URLspillerId;

                db.Entry(tblSpil).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index", new { URLspillerId });
            }
            ViewBag.CN_SpilSpillerPK = new SelectList(db.tblSpillers, "CN_SpillerPK", "CN_SpillerForNavn", tblSpil.CN_SpilSpillerPK);
            return View(tblSpil);
        }

        // GET: tblSpil/Delete/5
        public ActionResult Delete(int? id, int URLspillerId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblSpil tblSpil = db.tblSpils.Find(id);
            if (tblSpil == null)
            {
                return HttpNotFound();
            }

            ViewBag.SpillerNavn = FnHentNavneOpl(URLspillerId);

            return View(tblSpil);
        }

        // POST: tblSpil/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int URLspillerId)
        {
            tblSpil tblSpil = db.tblSpils.Find(id);
            db.tblSpils.Remove(tblSpil);
            db.SaveChanges();
            return RedirectToAction("Index", new { URLspillerId });
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        // Hent Fornavn og Efternavn på spiller
        private string FnHentNavneOpl(int URLspillerId)
        {
            if (URLspillerId == 0)
            {
                return ("Du kalder med værdien: 0, derfor ikke noget navn til dig basta.");
            }

            ViewBag.URLspillerId = URLspillerId;

            var spillerInfo = db.tblSpillers.FirstOrDefault(t => t.CN_SpillerPK == URLspillerId);
            return (spillerInfo.CN_SpillerForNavn + " " + spillerInfo.CN_SpillerEfterNavn);
        }
    }
}

NYKalleMaintV01/Views/Home/Create.cshtml
@model NYKalleMaintV01.Models.tblSpiller

@{
    ViewBag.Title = "Create";
}

<h2>Create - Spiller</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerForNavn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpillerForNavn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpillerForNavn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerEfterNavn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpillerEfterNavn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpillerEfterNavn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerInit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_SpillerInit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_SpillerInit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerOptDato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                 @Html.EditorFor(model => model.CN_SpillerOptDato, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.CN_SpillerOptDato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerUdMeldDato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                 @Html.EditorFor(model => model.CN_SpillerUdMeldDato, new { htmlAttributes = new { @class = "form-control" } })
                 @Html.ValidationMessageFor(model => model.CN_SpillerUdMeldDato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerFormand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpillerFormand)
                    @Html.ValidationMessageFor(model => model.CN_SpillerFormand, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerNastFormand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpillerNastFormand)
                    @Html.ValidationMessageFor(model => model.CN_SpillerNastFormand, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerKasser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpillerKasser)
                    @Html.ValidationMessageFor(model => model.CN_SpillerKasser, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerRevisor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpillerRevisor)
                    @Html.ValidationMessageFor(model => model.CN_SpillerRevisor, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerSkemaAnsv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpillerSkemaAnsv)
                    @Html.ValidationMessageFor(model => model.CN_SpillerSkemaAnsv, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_SpillerWebAnsv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_SpillerWebAnsv)
                    @Html.ValidationMessageFor(model => model.CN_SpillerWebAnsv, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CN_EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CN_EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_AktivMedl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_AktivMedl)
                    @Html.ValidationMessageFor(model => model.CN_AktivMedl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_PassivMedl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_PassivMedl)
                    @Html.ValidationMessageFor(model => model.CN_PassivMedl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CN_ProveMedl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CN_ProveMedl)
                    @Html.ValidationMessageFor(model => model.CN_ProveMedl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

NYKalleMaintV01/Views/Home/Delete.cshtml
@model NYKalleMaintV01.Models.tblSpiller

@{
    ViewBag.Title = "Delete";
}

<h2>Delete - Spiller</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<h3>Are you sure you want to delete this?</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerForNavn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerForNavn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerEfterNavn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerEfterNavn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerInit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerInit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerOptDato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerOptDato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerUdMeldDato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerUdMeldDato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerFormand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerFormand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerNastFormand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerNastFormand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerKasser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerKasser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerRevisor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerRevisor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerSkemaAnsv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerSkemaAnsv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerWebAnsv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerWebAnsv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_EMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_AktivMedl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_AktivMedl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_PassivMedl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_PassivMedl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_ProveMedl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_ProveMedl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

NYKalleMaintV01/Views/Home/Details.cshtml
@model NYKalleMaintV01.Models.tblSpiller

@{
    ViewBag.Title = "Details";
}

<h2>Details - Spiller</h2>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CN_SpillerPK }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerForNavn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerForNavn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerEfterNavn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerEfterNavn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerInit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerInit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerOptDato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerOptDato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerUdMeldDato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerUdMeldDato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerFormand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerFormand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerNastFormand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerNastFormand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerKasser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerKasser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerRevisor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerRevisor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerSkemaAnsv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerSkemaAnsv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_SpillerWebAnsv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_SpillerWebAnsv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_EMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_AktivMedl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_AktivMedl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_PassivMedl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_PassivMedl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CN_ProveMedl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CN_ProveMedl)
        </dd>

    </dl>
</div>

NYKalleMaintV01/Views/Home/Index.cshtml
@model IEnumerable<NYKalleMaintV01.Models.tblSpiller>

@{
    ViewBag.Title = "Index";
}

<h2>Index - Spiller</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpillerForNavn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CN_SpillerEfterNavn)
        </th>
        @*
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerInit)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerOptDato)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerUdMeldDato)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerFormand)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerNastFormand)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerKasser)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerRevisor)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerSkemaAnsv)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_SpillerWebAnsv)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_EMail)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_AktivMedl)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_PassivMedl)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.CN_ProveMedl)
    </th>
        *@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpillerForNavn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CN_SpillerEfterNavn)
        </td>
        @*
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerInit)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerOptDato)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerUdMeldDato)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerFormand)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerNastFormand)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerKasser)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerRevisor)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerSkemaAnsv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_SpillerWebAnsv)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_EMail)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_AktivMedl)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_PassivMedl)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.CN_ProveMedl)
    </td>
        *@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.CN_SpillerPK }) |
            @Html.ActionLink("Details", "Details", new { id = item.CN_SpillerPK }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.CN_SpillerPK }) |
            @Html.ActionLink("Games", "Index", "tblSpil", new { URLspillerId = item.CN_SpillerPK }, item.CN_SpillerPK)
        </td>
</tr>
}

</table>